In [134]:
#LAB-1
#Leader Array
a=[16,17,4,3,5,2]

n=len(a)
max=a[-1]
for i in range(0,n-1):
    for j in range(i+1,n-1):
        if a[i]<a[j]:
            print(a[j])
        else:
            break
        
        
print(max)

17
5
2


In [9]:
#Sorting Array
def zigzag_sort(a):
    n = len(a)

    # Sort the input list in ascending order
    a.sort()

    # Swap adjacent elements starting from index 1
    for i in range(1, n - 1, 2):
        a[i], a[i + 1] = a[i + 1], a[i]

a = [4, 3, 7, 8, 6, 2, 1]
zigzag_sort(a)
print("Zigzag ordered array:", a)


Zigzag ordered array: [1, 3, 2, 6, 4, 8, 7]


In [1]:
#LAB-2
#Triplet and their Sum
a=[12,3,4,1,6,9]
sum=24
n=len(a)
for i in range(n-2):
    j=n-1
    k=i+1
    if(a[i]+a[j]+a[k]==sum):
        print(a[i],a[j],a[k])
    

12 9 3


In [2]:
#Sorting an Array
a=[0,0,1,2,0,1,2,2,1]
n=len(a)
for i in range(n):
    for j in range(i+1,n):
        if a[i]<=a[j]:
            temp=a[i]
            a[i]=a[j]
            a[j]=temp
a.reverse()
print(a)

[0, 0, 0, 1, 1, 1, 2, 2, 2]


In [10]:
#LAB-3
#Removing Duplicate Values
a = [3, 2, 7, 3, 5, 2]
b = []

for i in a:
    if i not in b:
        b.append(i)

print(b)


[3, 2, 7, 5]


In [2]:
#To find whether the linked list has a loop or NOT
class Node:
    def __init__(self, value):
        self.value = value
        self.next = None

def find_loop(head):
    if head is None or head.next is None:
        return False

    slow = head
    fast = head.next

    while fast is not None and fast.next is not None:
        if slow == fast:
            return True
        slow = slow.next
        fast = fast.next.next

    return False


node1 = Node(1)
node2 = Node(2)
node3 = Node(3)
node4 = Node(4)

node1.next = node2
node2.next = node3
node3.next = node4
node4.next = node2  

print("to check if a linked list has a loop", find_loop(node1))


to check if a linked list has a loop True


In [13]:
#Time Complexity: N log N
def n_log_n(arr):
    sorted_arr = sorted(arr)
    return sorted_arr
arr = [4, 2, 7, 1, 9, 5]
print("Sorted array:", n_log_n(arr))


Sorted array: [1, 2, 4, 5, 7, 9]


In [7]:
#Maximum Sum
def max_sum(arr):
    if not arr:
        return 0

    max_sum = current_sum = arr[0]

    for num in arr[1:]:
        current_sum = max(num, current_sum + num)
        max_sum = max(max_sum, current_sum)

    return max_sum

arr = [1, -3, 4, -2, -1, 6]
print("Maximum sum of an arr:",max_sum(arr) )


Maximum sum of an arr: 7


In [11]:
#LAB-4
#Diagonal Interchange
import numpy as np


values = [0, 1, 2, 3,4, 5, 6, 7, 8]


matrix = np.array(values).reshape(3, 3)

print(matrix)
for i in range(3):
    for j in range(3):
        matrix[0][0],matrix[0][2]=matrix[0][2],matrix[0][0]
        matrix[2][0],matrix[2][2]=matrix[2][2],matrix[2][0]
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [3 4 5]
 [8 7 6]]


In [14]:
#Index Finder
def index(arr, num):
    indices = []
    for i in range(len(arr)):
        if arr[i] == num:
            indices.append(i)
    return indices

arr= [ 2, 7, 3, 9, 4, 5]
num= 4
print("find the element index:",index(arr, num))

find the element index: [4]


In [5]:
#LAB-5
#ROWS With Most No of One's
def with_most_ones(matrix):
    max_ones = 0
    row_index = -1

    for i, row in enumerate(matrix):
        count_ones = row.count(1)
        if count_ones > max_ones:
            max_ones = count_ones
            row_index = i

    return row_index


matrix = [
    [1, 0, 1, 1],
    [1, 1, 1, 1],
    [0, 0, 1, 1],
    [1, 0, 0, 1]
]


print("Row index with the most ones:",with_most_ones(matrix) )


Row index with the most ones: 1


In [6]:
#Middle Row and Column Sum
def row_column_sum(matrix):
    n = len(matrix)
    middle = n // 2
    row_sum = sum(matrix[middle])
    col_sum = sum(row[middle] for row in matrix)

    return row_sum, col_sum


matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

row_sum, col_sum = row_column_sum(matrix)
print("Sum of the middle row:", row_sum)
print("Sum of the middle column:", col_sum)


Sum of the middle row: 15
Sum of the middle column: 15


In [24]:
#LAB-6
#sort the  given matrix and replace diagnols with zero
import numpy as np


values =[7,6,5,1,2,3,8,4,9]


matrix = np.array(values).reshape(3, 3)
print(matrix)
for i in range(len(values)-1):
    for j in range(i+1,len(values)):
        if values[i]>values[j]:
            temp=values[i]
            values[i],values[j]=values[j],values[i]
matrix = np.array(values).reshape(3, 3)
print(matrix)
            
for i in range(4):
    for j in range(4):
        if(i==0 and j==0):
            matrix[i][j]=0
            print(matrix)
for i in range(4):
    for j in range(4):
        if(i==1 and j==1):
            matrix[i][j]=0
            print(matrix)
for i in range(4):
    for j in range(4):
        if(i==2 and j==2):
            matrix[i][j]=0
            print(matrix)
for i in range(4):
    for j in range(4):
        if(i==0 and j==2):
            matrix[i][j]=0
            print(matrix)
for i in range(4):
    for j in range(4):
        if(i==2 and j==0):
            matrix[i][j]=0
            print(matrix)




[[7 6 5]
 [1 2 3]
 [8 4 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 0 6]
 [7 8 9]]
[[0 2 3]
 [4 0 6]
 [7 8 0]]
[[0 2 0]
 [4 0 6]
 [7 8 0]]
[[0 2 0]
 [4 0 6]
 [0 8 0]]


In [15]:
#Integer Multiplication without Operators
def multiply(x, y):
    if y == 0:
        return 0
    if y > 0:
        return x + multiply(x, y - 1)
    if y < 0:
        return -multiply(x, -y)
    


result = multiply(5, 3)
print(result) 

15


In [16]:
#LAB-7
#Binary Search Tree Node Search
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

def search_tree(node, value):
    if node is None:
        return False
    if node.value == value:
        return True
    return search_tree(node.left, value) or search_tree(node.right, value)

root = Node(10)
root.left = Node(8)
root.right = Node(20)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.right = Node(21)
root.right.left = Node(15)

a = int(input("Enter the value you want to search for: "))

if search_tree(root, a):
    print("Searching element is found.")
else:
    print("Searching element is not found.")


Enter the value you want to search for: 8
Searching element is found.


In [3]:
#Leaf Node Sum in a Tree
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None
def print_tree(node):
    if node is not None:
        print(node.value)
        print_tree(node.left)
        print_tree(node.right)
def sum_leaf_nodes(node):
    if node is None:
        return 0
    if node.left is None and node.right is None:
        return node.value
    return sum_leaf_nodes(node.left) + sum_leaf_nodes(node.right)

root = Node(10)
root.left = Node(8)
root.right = Node(20)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.right = Node(21)
root.right.left = Node(15)
print_tree(root)
leaf_sum = sum_leaf_nodes(root)
print("Sum of leaf nodes:", leaf_sum)


10
8
7
9
20
15
21
Sum of leaf nodes: 52


In [22]:
#Spinal (Zig-Zag) Order Tree Traversa
class TreeNode:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

def spiral_traversal(root):
    if not root:
        return

    
    current_level = []
    next_level = []

    
    left_to_right = True

    current_level.append(root)

    while current_level:
        node = current_level.pop()
        print(node.value, end=" ")

        if left_to_right:
            if node.left:
                next_level.append(node.left)
            if node.right:
                next_level.append(node.right)
        else:
            if node.right:
                next_level.append(node.right)
            if node.left:
                next_level.append(node.left)

        if not current_level:
            current_level, next_level = next_level, current_level
            left_to_right = not left_to_right


root = TreeNode(1)
root.left = TreeNode(2)
root.right = TreeNode(3)
root.left.left = TreeNode(4)
root.left.left.left=TreeNode(8)
root.left.left.right=TreeNode(9)
root.left.right = TreeNode(5)
root.left.right.right = TreeNode(11)
root.left.right.left = TreeNode(10)
root.right.right = TreeNode(7)
root.right.right.right = TreeNode(15)
root.right.right.left = TreeNode(14)
root.right.left=TreeNode(6)
root.right.left.left=TreeNode(12)
root.right.left.right=TreeNode(13)




print("Spiral Order Traversal:")
spiral_traversal(root)


Spiral Order Traversal:
1 3 2 4 5 6 7 15 14 13 12 11 10 9 8 